name: Run ML Script

on: [push]

jobs:
  run-python:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - run: pip install scikit-learn numpy pandas matplotlib

      - run: python ml.py
